FROM node:18-alpine

WORKDIR /app

RUN apk update && apk add --no-cache bash

COPY package*.json ./

RUN npm ci

COPY . .

# Define build arguments and environment variables
ARG DATABASE_URL
ARG RESEND_API_KEY
ARG COHERE_API_KEY
ARG PUSHER_APP_ID
ARG PUSHER_SECRET
ARG NEXT_PUBLIC_PUSHER_KEY
ARG NEXT_PUBLIC_PUSHER_CLUSTER

ENV DATABASE_URL=${DATABASE_URL}
ENV RESEND_API_KEY=${RESEND_API_KEY}
ENV COHERE_API_KEY=${COHERE_API_KEY}
ENV PUSHER_APP_ID=${PUSHER_APP_ID}
ENV PUSHER_SECRET=${PUSHER_SECRET}
ENV NEXT_PUBLIC_PUSHER_KEY=${NEXT_PUBLIC_PUSHER_KEY}
ENV NEXT_PUBLIC_PUSHER_CLUSTER=${NEXT_PUBLIC_PUSHER_CLUSTER}

RUN npx prisma generate

# Build the application
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
