version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: unless-stopped

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        RESEND_API_KEY: ${RESEND_API_KEY}
        COHERE_API_KEY: ${COHERE_API_KEY}
    expose:
      - "3000"
    environment:
      - DATABASE_URL
      - RESEND_API_KEY
      - COHERE_API_KEY
    restart: unless-stopped
